FROM php:7.3-fpm

ARG server_name
ARG www_user
ARG MAIL_USER
ARG MAIL_PASSWORD
ARG MAIL_HUB
ARG MAIL_PORT

# Install extensions
RUN apt-get update \
	&& apt-get install -y libicu-dev zip unzip curl zlib1g-dev libpng-dev vim procps iproute2 git gettext-base msmtp \
	&& docker-php-ext-install intl opcache \
	&& docker-php-ext-enable intl opcache \
	&& docker-php-ext-install pdo pdo_mysql mysqli\
	&& docker-php-ext-install mbstring \
	&& pecl install xdebug-2.7.1 \
	&& docker-php-ext-enable xdebug \
	&& docker-php-ext-install gd \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./msmtprc /etc/msmtprc.tpl
RUN envsubst '$$MAIL_USER$$$MAIL_PASSWORD$$MAIL_HUB$$MAIL_PORT' < /etc/msmtprc.tpl > /etc/msmtprc

COPY ./www.conf.template /usr/local/etc/php-fpm.d/zz-docker.conf.template
RUN envsubst '$$www_user' < /usr/local/etc/php-fpm.d/zz-docker.conf.template > /usr/local/etc/php-fpm.d/zz-docker.conf

RUN test -d /sock || mkdir /sock; \
	chmod -R +x /sock

WORKDIR /var/www/app