version: '3'
services:
   web:
      build:
         context: ./docker/nginx
         dockerfile: Dockerfile.dev
         args:
            server_name: ${server_name}
      container_name: aydev-nginx
      depends_on:
      - php
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/sock
      - ./docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./docker/nginx/conf.d/default.local.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./docker/log/nginx:/var/log/nginx
      env_file:
      - ./.env.docker
      ports:
      - 8080:80
      networks:
      - dev
      command: >
         /bin/sh -c
         "envsubst '$$server_name' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
         && envsubst '$$www_user' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
         && nginx -g 'daemon off;'"

   db:
      image: mariadb:10.4
      container_name: aydev-mariadb
      depends_on:
      - php
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      ports:
      - 3306:3306
      networks:
      - dev

   php:
      build:
         context: ./docker/php
         dockerfile: Dockerfile.dev
         args:
            www_user: ${www_user}
            www_password: ${www_password}
            server_name: ${server_name}
      container_name: aydev-php
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/sock
      - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
      env_file:
      - ./.env.docker
      expose:
      - 9000
      - 9001
      environment:
         TIMEZONE: ${TIMEZONE}
         LANGUAGE: ${LANGUAGE}
      networks:
      - dev

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:

networks:
   dev:
