version: '3'
services:
   web:
      build:
         context: ./docker/nginx
         dockerfile: Dockerfile.prod
         args:
            server_name: ${server_name}
            TIMEZONE: ${TIMEZONE}
      container_name: ay-web
      ports:
      - 80:80
      - 443:443
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/var/run
      - ./docker/nginx/nginx.prod.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/conf.d/default.prod.conf:/usr/local/openresty/nginx/conf/server-proxy.conf
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/nginx/logrotate.d/nginx:/etc/logrotate.d/nginx
      - ssl-data:/etc/resty-auto-ssl
      env_file:
      - ./.env.docker
      restart: on-failure
      environment:
         ALLOWED_DOMAINS: ${server_name}
         SITES: ${server_name}=web:80
         LETSENCRYPT_URL: ${LETSENCRYPT_URL}
      networks:
         app-network:
            ipv4_address: 172.30.0.2

   php:
      build:
         context: ./docker/php
         dockerfile: Dockerfile.prod
         args:
            www_password: ${www_password}
            server_name: ${server_name}
            TIMEZONE: ${TIMEZONE}
      container_name: ay-phpfpm
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/var/run
      - ./docker/php/php.prod.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      env_file:
      - ./.env.docker
      environment:
         TIMEZONE: ${TIMEZONE}
         LANGUAGE: ${LANGUAGE}
      networks:
         app-network:
            ipv4_address: 172.30.0.3
      restart: always

   nodejs:
      image: node:${NODE_VERSION}-alpine
      container_name: ay-node
      volumes:
      - document-volume:/var/www/app:cached
      networks:
         app-network:
      restart: always

   db:
      image: mariadb:10.4
      container_name: ay-mariadb
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      ports:
      - 3306:3306
      networks:
         app-network:
            ipv4_address: 172.30.0.4
      restart: always

   redis:
      image: redis:5-alpine
      ports:
      - 6379:6379
      networks:
         app-network:

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:
   ssl-data:

networks:
   app-network:
      driver: bridge
      ipam:
         config:
            - subnet: '172.30.0.0/16'
