version: '3'
services:
   web:
      build:
         context: ./docker/nginx
         dockerfile: prod.Dockerfile
      container_name: ay-web
      ports:
      - 8080:80
      - 443:443
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/var/run
      - ./docker/nginx/nginx.prod.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx:/var/log/nginx
      - ssl-data:/etc/resty-auto-ssl
      env_file:
      - ./.env.docker
      restart: on-failure
      environment:
         ALLOWED_DOMAINS: ${server_name}
         SITES: ${server_name}:8080=web:80
      networks:
      - app-network

   db:
      image: mariadb:10.4
      container_name: ay-mariadb
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      ports:
      - 3306:3306
      networks:
      - app-network
      restart: always

   php:
      build:
         args:
            www_user: ${www_user}
            www_password: ${www_password}
            NODE_VERSION: ${NODE_VERSION}
         context: ./docker/php
      container_name: ay-phpfpm
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/var/run
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      env_file:
      - ./.env.docker
      environment:
         TIMEZONE: Asia/Tokyo
         LANGUAGE: "Japanese"
         NVM_DIR:
      networks:
      - app-network
      restart: always

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:
   ssl-data:

networks:
   app-network:
