version: '3'
services:
   web:
      build:
         context: ./docker/nginx
         dockerfile: Dockerfile.dev
      container_name: aydev-nginx
      depends_on:
      - php
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/var/run
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.local.conf:/etc/nginx/conf.d/default.local.conf
      - ./docker/log/nginx:/var/log/nginx
      env_file:
      - ./.env.docker
      ports:
      - 8080:80
      - 443:443
      networks:
      - app-network
      entrypoint: nginx -g 'daemon off;'

   db:
      image: mariadb:10.4
      container_name: aydev-mariadb
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      ports:
      - 3306:3306
      networks:
      - app-network

   php:
      build:
         context: ./docker/php
         dockerfile: Dockerfile.dev
         args:
            www_user: ${www_user}
            www_password: ${www_password}
            NODE_VERSION: ${NODE_VERSION}
      container_name: aydev-php
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/var/run
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      env_file:
      - ./.env.docker
      expose:
      - 9000
      - 9001
      environment:
         TIMEZONE: ${TIMEZONE}
         LANGUAGE: ${LANGUAGE}
         NVM_DIR:
      networks:
      - app-network

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:

networks:
   app-network:
