version: '3'
services:
   web:
      build:
         context: ./docker/nginx
         dockerfile: Dockerfile.prod
         args:
            www_user: ${www_user}
            server_name: ${server_name}
            TIMEZONE: ${TIMEZONE}
            LOCAL_UID: ${LOCAL_UID}
            LOCAL_GID: ${LOCAL_GID}
      container_name: ay-web
      depends_on:
      - php
      ports:
      - 5000:5000
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/sock
      - ./docker/nginx/nginx.prod.conf.template:/etc/nginx/nginx.conf.template
      - ./docker/nginx/conf.d/prod.conf.template:/etc/nginx/conf.d/web.conf.template
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/nginx/logrotate.d/nginx:/etc/logrotate.d/nginx
      env_file:
      - ./.env.docker
      restart: on-failure
      networks:
         app-network:
            ipv4_address: 172.30.0.10
      command: >
            /bin/sh -c
            "envsubst '$$server_name$$STAGE_ENV' < /etc/nginx/conf.d/web.conf.template > /etc/nginx/conf.d/web.conf
            && envsubst '$$www_user' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
            && nginx -g 'daemon off;'"

   php:
      build:
         context: ./docker/php
         dockerfile: Dockerfile.prod
         args:
            www_user: ${www_user}
            www_password: ${www_password}
            server_name: ${server_name}
            TIMEZONE: ${TIMEZONE}
            LOCAL_UID: ${LOCAL_UID}
            LOCAL_GID: ${LOCAL_GID}
      container_name: ay-phpfpm
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/sock
      - ./docker/php/php.prod.ini:/usr/local/etc/php/php.ini
      env_file:
      - ./.env.docker
      networks:
         app-network:
            ipv4_address: 172.30.0.13
      restart: always

   https:
      image: steveltn/https-portal:1
      container_name: ay-https
      environment:
         DOMAINS: '${server_name} -> http://web:5000'
         STAGE: ${STAGE_ENV}
      depends_on: 
      - web
      ports: 
      - 80:80
      - 443:443
      networks:
         app-network:

   db:
      image: mariadb:10.4
      container_name: ay-mariadb
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      depends_on:
      - php
      ports:
      - 3306:3306
      networks:
         app-network:
            ipv4_address: 172.30.0.15
      restart: always

   redis:
      build:
         context: ./docker/redis
      container_name: ay-redis
      depends_on:
      - php
      - db
      ports:
      - 6379:6379
      networks:
         app-network:

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:
   ssl-data:

networks:
   app-network:
      driver: bridge
      ipam:
         config:
            - subnet: '172.30.0.0/16'
