FROM nginx:1.15

ARG server_name

RUN apt-get update \
	&& apt-get install -y openssl
RUN mkdir -p /var/www/app

RUN openssl genrsa 2048 > server.key \
	&& openssl req -new -key server.key -subj "/C=JP/ST=Tokyo/L=Chuo-ku/O=RMP Inc./OU=web/CN=localhost" > server.csr \
	&& openssl x509 -in server.csr -days 3650 -req -signkey server.key > server.crt \
	&& cp server.crt /etc/nginx/server.crt \
	&& cp server.key /etc/nginx/server.key \
	&& chmod 755 -R /var/www/app

ENTRYPOINT ["sed", "-i", "-e", 's/\${server_name}/'"${server_name}"'/g', "/etc/nginx/conf.d/default.local.conf"]

USER ${www_user}
