FROM nginx:1.17.3

ARG server_name

RUN apt-get update \
	&& apt-get install -y openssl gettext-base

RUN openssl genrsa 2048 > server.key \
	&& openssl req -new -key server.key -subj "/C=JP/ST=Tokyo/L=Chuo-ku/O=RMP Inc./OU=web/CN=${server_name}" > server.csr \
	&& openssl x509 -in server.csr -days 3650 -req -signkey server.key > server.crt \
	&& cp server.crt /etc/nginx/server.crt \
	&& cp server.key /etc/nginx/server.key